### ISSUE TITLE
from trading import SpreadTrading ImportError: No module named 'trading'

### ISSUE THREAD

**Issue by forhonourlx** [Prediction-Machines/Trading-Brain#3]
Traceback (most recent call last):
  File "keras_example.py", line 11, in <module>
    from tgym.envs import SpreadTrading
  File "C:\Program Files\Python35\lib\site-packages\tgym\envs\__init__.py", line 1, in <module>
    from trading import SpreadTrading
ImportError: No module named 'trading'

**Comment by pm-beba** [comment]
We are having a look

**Comment by laksefest** [comment]
Im also getting this error. Would appreciate if you could look into it. The project seems very interesting :)

**Comment by vadivukkarasi-c** [comment]
#

**Comment by vadivukkarasi-c** [comment]
>
